#!/bin/bash

# Script to clean up repository by removing large files and build artifacts
# This should be run before pushing to avoid pushing large .dmg files

set -e

echo "🧹 Cleaning up repository..."

# Remove .dmg files from public/downloads (these will be generated by GitHub Actions)
echo "Removing .dmg files from public/downloads..."
rm -f frontend/public/downloads/*.dmg
rm -f frontend/public/downloads/*.dmg.blockmap

# Remove .dmg files from out/downloads
echo "Removing .dmg files from out/downloads..."
rm -f frontend/out/downloads/*.dmg
rm -f frontend/out/downloads/*.dmg.blockmap

# Remove dist folder (build artifacts)
echo "Removing dist folder..."
rm -rf frontend/dist/

# Remove out folder (Next.js build output)
echo "Removing out folder..."
rm -rf frontend/out/

# Remove any other build artifacts
echo "Removing other build artifacts..."
find . -name "*.dmg" -not -path "./.git/*" -delete
find . -name "*.dmg.blockmap" -not -path "./.git/*" -delete
find . -name "*.app" -not -path "./.git/*" -delete

echo "✅ Repository cleaned up!"
echo ""
echo "📝 Next steps:"
echo "1. Add and commit the changes:"
echo "   git add ."
echo "   git commit -m 'Clean up repository and remove build artifacts'"
echo ""
echo "2. Push your feature branch:"
echo "   git push origin feature/minimalist-design"
echo ""
echo "3. Create a release using GitHub UI or the release script"
echo ""
echo "💡 The .dmg files will be automatically generated and uploaded to GitHub Releases!"
